Algoritmo "Concatenação"
// 
//  
// Descrição   : Operadores de Concatenação
// Autor(a)    : Richard de Lucena Ribeiro
// Data atual  : 20/4/2020
Var
// Seção de Declarações das variáveis 
   nome:caractere
   numero:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite o nome:")
   leia(nome)
   escreval("Digite o número:")
   leia(numero)
   
   escreval(nome,":",numero, 99)
   
Fimalgoritmo