Algoritmo "Meu primeiro algoritmo"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Antônio Carlos Nicolodi
// Autor(a)    : Richard de Lucena Ribeiro
// Data atual  : 14/4/2020
Var
// Seção de Declarações das variáveis 
   nota: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   nota <- 100
   escreva ("Resultado:",nota)
Fimalgoritmo